# Generated by Django 6.0 on 2025-12-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
