# Generated by Django 6.0 on 2025-12-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_journalentry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
