# Generated by Django 6.0 on 2025-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name shown throughout the app (falls back to full name or username)', max_length=100),
        ),
    ]
