# Generated by Django 6.0 on 2025-12-22 15:39

import apps.journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, default=apps.journal.models.default_title, max_length=255),
        ),
    ]
