# Generated by Django 6.0 on 2025-12-22 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_date']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
